name: authwebview
description: A Flutter package for OAuth authentication using WebView.
version: 1.0.1
homepage: https://github.com/hakanmertb/authwebview

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_inappwebview: ^6.1.3
  device_info_plus: any
  crypto: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: